# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPP_computing_kernel <- function(x, max_kmer_length, exponential) {
    .Call(`_kernelForLeon_CPP_computing_kernel`, x, max_kmer_length, exponential)
}

